### ISSUE TITLE
Definitions and using true or false statements

### ISSUE THREAD

**Issue by RMcD94** [9Axes/9axes.github.io#19]
Statements like "X always Y" are almost always false and as such strongly disagree because of a single example in history.

Similarly "X never Y" has the same implication.

"X sometimes Y" is also almost always true sometimes only needs 2 times. So local government sometimes makes a better decision than national government. Has any local government in the entire history of humanity ever made a superior choice from a national government? Obviously. I hate local governments yet I can acknowledge this.

Also wtf do you mean "should" "must", etc. If the questions do not follow the exact same layout and specifications then inconsistencies in question proposal manipulate answers. I might think it's better if everyone is gassed but it doesn't mean that I think it "must" happen. It's not a definition. 

Also the framing of everything as if it's American seems unneeded. Why "states" instead of first level administrative divisions?" 

Also from what perspective am I meant to answer this quiz? From what I want my government to be or from what I would do if I was in charge of government? What's good for me doesn't always follow that it's good for the country/people/state/earth/etc

**Comment by 9Axes** [comment]
"Statements like "X always Y" are almost always false and as such strongly disagree because of a single example in history. Similarly "X never Y" has the same implication." - That's your opinion, as Y is usually open to interpretation. You also might be taking those a bit too literally, if 99% of the time it's true, you can probably say that. Though if you say that something is not always true, that also means you recognize it can be false, which is a political belief. Y is usually open to interpretation.

"X sometimes Y" is also almost always true sometimes only needs 2 times. So local government sometimes makes a better decision than national government. Has any local government in the entire history of humanity ever made a superior choice from a national government? Obviously. I hate local governments yet I can acknowledge this.
Yes, that's the point. Each axis has multiple levels, going from moderate statements most people can agree with, to extreme ones that only devoted fanatics of the axis would agree with.

Also wtf do you mean "should" "must", etc. If the questions do not follow the exact same layout and specifications then inconsistencies in question proposal manipulate answers. I might think it's better if everyone is gassed but it doesn't mean that I think it "must" happen. It's not a definition.
Again, there's multiple levels of intensity. It takes these levels into account when determining the score, if they had the same layout and specifications it wouldn't work right.

Also the framing of everything as if it's American seems unneeded. Why "states" instead of first level administrative divisions?"
There was already another issue to change this to provinces, which I said if someone made a merge request, I'd accept it. Nobody has yet done so, I might get around to it at some point.

Also from what perspective am I meant to answer this quiz? From what I want my government to be or from what I would do if I was in charge of government? What's good for me doesn't always follow that it's good for the country/people/state/earth/etc
Depends. If you want the political alignment of what you want your government to be, take it from that perspective. If you want the alignment of what a government run by you would be, take it from that perspective. In other words, take it from the perspective that you want the results from.
